<?php
/*
 * This file is part of jsonapi the package.
 *
 * (c) Alexey Astafev <efsneiron@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RonteLtd\CommonBundle\Tests\Entity;

use RonteLtd\CommonBundle\Entity\EntityServiceInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * EntityServiceTest
 *
 * @author Alexey Astafev <efsneiron@gmail.com>
 */
class EntityServiceTest extends WebTestCase
{
    /**
     * @var \Symfony\Component\Validator\Validator\ValidatorInterface
     */
    private $validator;

    /**
     * @var \RonteLtd\CommonBundle\Tests\Entity\EntityRepository
     */
    private $repository;

    /**
     * @inheritdoc
     */
    public function setUp()
    {
        $client = self::createClient();
        $this->validator = $client->getContainer()->get('validator');
        $this->repository = $client
            ->getContainer()
            ->get('doctrine')
            ->getRepository('RonteLtd\CommonBundle\Tests\Entity\Entity');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Tests constructor
     */
    public function testConstruct()
    {
        new EntityService($this->validator);
    }

    /**
     * Tests setter and gettter of the EntityService
     *
     * @covers \RonteLtd\CommonBundle\Tests\Entity\EntityService::setRepository()
     * @covers \RonteLtd\CommonBundle\Tests\Entity\EntityService::getRepository()
     */
    public function testGetSetRepository()
    {
        $service = new EntityService($this->validator);
        self::assertInstanceOf(
            'RonteLtd\CommonBundle\Entity\EntityServiceInterface', $service->setRepository($this->repository));
        self::assertEquals($this->repository, $service->getRepository());
    }

    /**
     * Test validate
     *
     * @covers \RonteLtd\CommonBundle\Tests\Entity\EntityService::validate()
     */
    public function testValidate()
    {
        $service = new EntityService($this->validator);
        $entity = new Entity([]);
        $result = $service->validate($entity);
        self::assertNotEmpty($result['firstname']);
        $result = $service->validate($entity->setFirstname('Vasia'));
        self::assertInstanceOf('RonteLtd\CommonBundle\Tests\Entity\Entity', $result);
    }
}