<?php
/*
 * This file is part of CommonBundle the package.
 *
 * (c) Alexey Astafev <efsneiron@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RonteLtd\CommonBundle\Tests\Entity;

use Liip\FunctionalTestBundle\Test\WebTestCase;

/**
 * EntityRepositoryTest
 *
 * @author Alexey Astafev <efsneiron@gmail.com>
 */
class EntityRepositoryTest extends WebTestCase
{
    private $client;

    /**
     * @var \RonteLtd\CommonBundle\Tests\Entity\EntityRepository
     */
    private $repository;

    public function setUp()
    {
        $this->client = $client = static::createClient();

        $this->repository = $this->client
            ->getContainer()
            ->get('doctrine')
            ->getRepository('RonteLtd\CommonBundle\Tests\Entity\Entity');
        $this->loadFixtures(array(
            'RonteLtd\CommonBundle\Tests\DataFixtures\ORM\LoadEntityData',
        ));

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Tests save
     * @covers \RonteLtd\CommonBundle\Tests\Entity\EntityRepository::save()
     */
    public function testSave()
    {
        $entity = $this->repository->find(1);
        $entity = $this->repository->save($entity->setFirstname('xman'));
        self::assertInstanceOf('RonteLtd\CommonBundle\Tests\Entity\Entity', $entity);
        self::assertEquals('xman', $entity->getFirstname());
    }

    /**
     * Tests remove
     * @covers \RonteLtd\CommonBundle\Tests\Entity\EntityRepository::remove()
     */
    public function testRemove()
    {
        $entity = $this->repository->find(1);
        $entity = $this->repository->remove($entity);
        $reflection = new \ReflectionProperty($entity, 'id');
        $reflection->setAccessible(true);
        self::assertInstanceOf('RonteLtd\CommonBundle\Tests\Entity\Entity', $entity);
        self::assertNull($reflection->getValue($entity));
    }
}