<?php

/*
 * This file is part of CommonBundle the package.
 *
 * (c) Alexey Astafev <efsneiron@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace RonteLtd\CommonBundle\Tests\Entity;

use PHPUnit\Framework\TestCase;

/**
 * EntityTest
 *
 * @author Alexey Astafev <efsneiron@gmail.com>
 */
class EntityTest extends TestCase
{
    private $data;

    /**
     * @inheritdoc
     */
    public function setUp()
    {
        $this->data = [
            'firstname' => 'Vasya',
            'lastname' => 'Pupkin'
        ];

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Tests construct
     */
    public function testConstruct()
    {
        $entity = new Entity($this->data);

        self::assertEquals('Vasya', $entity->getFirstname());
        self::assertNotEquals('Pupkin', $entity->getLastname());
    }

    /**
     * Tests FromArray
     * @covers \RonteLtd\CommonBundle\Tests\Entity\Entity::fromArray()
     */
    public function testFromArray()
    {
        $entity = new Entity([]);
        $entity->fromArray($this->data);

        self::assertEquals('Vasya', $entity->getFirstname());
        self::assertNotEquals('Pupkin', $entity->getLastname());
    }
}